blank_issues_enabled: true
contact_links:
  - name: Read the Documentation
    url: https://github.com/ryanbekhen/ngebut#readme
    about: Check if your question is already answered in the documentation